### ISSUE TITLE
Compile errors when running .\node_modules\.bin\electron-rebuild.cmd

### ISSUE THREAD

**Issue by HowdyMoto** [BETAFPV/BETAFPV_Configurator#40]
Hello,

I am trying to compile the BetaFPV configurator in order to fix some bugs. When I try to build it, I get the following errors. Can you help identify what the issue is here?

```
An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'D:\GitHub\BETAFPV_Configurator\node_modules\@serialport\bindings'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `gyp` failed with exit code: 1



Error: node-gyp failed to rebuild 'D:\GitHub\BETAFPV_Configurator\node_modules\@serialport\bindings'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `gyp` failed with exit code: 1


    at NodeGyp.rebuildModule (D:\GitHub\BETAFPV_Configurator\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:120:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleRebuilder.rebuildNodeGypModule (D:\GitHub\BETAFPV_Configurator\node_modules\electron-rebuild\lib\src\module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (D:\GitHub\BETAFPV_Configurator\node_modules\electron-rebuild\lib\src\module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (D:\GitHub\BETAFPV_Configurator\node_modules\electron-rebuild\lib\src\rebuild.js:149:13)
    at async Rebuilder.rebuild (D:\GitHub\BETAFPV_Configurator\node_modules\electron-rebuild\lib\src\rebuild.js:112:17)
    at async D:\GitHub\BETAFPV_Configurator\node_modules\electron-rebuild\lib\src\cli.js:158:9
```

**Comment by HowdyMoto** [comment]
Actually - I found the error. Installing the latest npm installs Python 3.12. When you use nvm to switching to npm 16.20.0, the python version stays at 3.12. I'll submit a PR to the README that notes that.
